---
branches: ["main"]
preset: "cargo"
tagFormat: "${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets: ["CHANGELOG.md", "package.json", "**/Cargo.toml"]
  - "@semantic-release/github"
  - "@semantic-release-cargo/semantic-release-cargo"
