name: Rust

on:
  # Triggers the workflow on push or pull request events.
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"
  pull_request: {}
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.CODR_WORKFLOW_TOKEN }}
  GH_TOKEN: ${{ secrets.CODR_WORKFLOW_TOKEN }}
  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_KEY }}
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  RUST_BACKTRACE: 1

jobs:
  # Save next release version as GitHub Actions outputs
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4
    permissions:
      contents: write

  # Setups up the rest of the jobs with tools
  setup:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.rust_os.os }}

    strategy:
      fail-fast: false
      matrix:
        rust_os:
          - { rust: 1.72.0, os: ubuntu-20.04 }

    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        id: rust-toolchain
        with:
          toolchain: ${{ matrix.rust_os.rust }}
          override: true
          components: clippy, rustfmt

      - name: Download semantic-release-rust
        run: cargo install semantic-release-rust --version 1.0.0-alpha.8

      - name: Build (to get dependencies)
        run: cargo build --verbose

      - name: Cache Rust toolchain
        uses: actions/cache/save@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ job.setup.steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

  # Checks to see if linting and formatting has been adhered to
  checks:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.rust_os.os }}
    needs:
      - setup

    strategy:
      fail-fast: false
      matrix:
        rust_os:
          - { rust: 1.72.0, os: ubuntu-20.04 }

    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - uses: actions/checkout@v3

      - name: Clippy
        if: ${{ matrix.rust_os.rust == '1.72.0' }}
        run: cargo clippy --all --all-features -- --deny warnings

      - name: Check fmt
        if: ${{ matrix.rust_os.rust == '1.72.0' }}
        run: cargo fmt --all -- --check

  # Tests the packages in the repo
  tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.rust_os.os }}
    needs:
      - setup

    strategy:
      fail-fast: false
      matrix:
        rust_os:
          - { rust: 1.72.0, os: ubuntu-20.04 }

    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: cargo test --verbose

  # Compiles packages
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.rust_os.os }}
    needs:
      - setup
      - checks
      - tests

    strategy:
      fail-fast: false
      matrix:
        rust_os:
          - { rust: 1.72.0, os: ubuntu-20.04 }

    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

  # Dry run of semantic-release
  semantic-release-dry-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs:
      - get-next-version
      - setup

    env:
      GITHUB_TOKEN: ${{ secrets.CODR_WORKFLOW_TOKEN }}
      GH_TOKEN: ${{ secrets.CODR_WORKFLOW_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare semantic-release for Rust
        if: needs.get-next-version.outputs.new-release-published == 'true'
        run: semantic-release-rust prepare ${{ needs.get-next-version.outputs.new-release-version }}

      - name: Semantic Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_KEY }}
        uses: cycjimmy/semantic-release-action@v4
        with:
            extra_plugins: |
              @semantic-release/git
              @semantic-release/github
              @semantic-release/exec
            dry_run: true

  # --- Jobs that only on successful pushes to main ---
  semantic-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs:
      - get-next-version
      - semantic-release-dry-run
    if: github.ref == 'refs/heads/main'

    env:
      GITHUB_TOKEN: ${{ secrets.CODR_WORKFLOW_TOKEN }}
      GH_TOKEN: ${{ secrets.CODR_WORKFLOW_TOKEN }}
      ACTIONS_RUNNER_DEBUG: true

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare semantic-release for Rust
        if: needs.get-next-version.outputs.new-release-published == 'true'
        run: semantic-release-rust prepare ${{ needs.get-next-version.outputs.new-release-version }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CODR_WORKFLOW_TOKEN }}
        with:
            extra_plugins: |
              @semantic-release/git
              @semantic-release/github
              @semantic-release/exec
