name: Rust

on:
  # Triggers the workflow on push or pull request events.
  push: {}
  pull_request: {}
  # schedule:
  #   # Run daily to catch breakages in new Rust versions as well as new cargo audit findings.
  #   - cron: '0 16 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.rust_os.os }}

    strategy:
      fail-fast: false
      matrix:
        rust_os:
          - { rust: 1.66.0, os: ubuntu-20.04 }
          - { rust: stable, os: ubuntu-latest }
          - { rust: beta, os: ubuntu-latest }
          - { rust: nightly, os: ubuntu-latest }

    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - uses: actions/checkout@v3
        
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_os.rust }}
          override: true
          components: clippy, rustfmt

      - name: Clippy
        if: ${{ matrix.rust_os.rust == '1.66.0' }}
        run: cargo clippy --all --all-features -- --deny warnings

      - name: Check fmt
        if: ${{ matrix.rust_os.rust == '1.66.0' }}
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
